name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install twine
        run: |
          pip install twine
          pip install wheel
          pip install setuptools
      - name: Upload wheel
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_NON_INTERACTIVE: 1
        run: |
          python setup.py bdist_wheel
          twine upload dist/*.whl